Cherry pick of 31e8334f1edfbf1717717288b4eceb420080ca90 failed
stdout:

stderr:
error: could not apply 31e8334f1ed... [FIX] website_event_*: fix minor view/wording issues
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'